version: '3.8'

services:
  nas-app:
    build:
      context: .
      target: production
    container_name: nas-application
    ports:
      - "8086:7777"
    volumes:
      # 새로운 통합 경로 시스템 사용
      # DATA_PATH 환경변수를 기반으로 모든 경로 자동 결정
      - ${DATA_PATH:-/mnt/nas-storage}/files:/app/data/files
      - ${DATA_PATH:-/mnt/nas-storage}/admin:/app/data/admin
      - ${DATA_PATH:-/mnt/nas-storage}/database:/app/data/database
      - ${DATA_PATH:-/mnt/nas-storage}/temp:/app/data/temp
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATA_PATH=/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7777/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

# 볼륨 대신 호스트 마운트 사용 (RAID 직접 연결)
# 기존 네트워크 설정 제거 (단순화)